---
title: Ellison Homestead
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: We've decided to pursue our dream of living a more simple and sustainable
  life whilst serving some of the world's deepest needs.
url: http://ellisonhomestead.com
twitter_username: iamjohnellison
email: john@john-ellison.com
include:
- _pages
markdown: kramdown
baseurl: ''
permalink: pretty
gems:
- jekyll-sitemap
- 
