---
title: Ellison Homestead — Our family's journey to living a more simple  and sustainable
  life whilst trying to serve the world's deepest needs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
markdown: kramdown
mail: john@john-ellison.com
description: In 2016 John and Sophie Ellison decided to start a smallholding outside
  Norwich, Norfolk in the UK. This website shares their learning, hardship and triumphs.
baseurl: 
url: http://ellisonhomestead.com
twitter_username: iamjohnellison
github_username: johnellison
permalink: pretty
gems:
- jekyll-sitemap
- 
